apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      color: blue
  template:
    metadata:
      labels:
        app: sample-app
        color: blue
    spec:
      containers:
        - name: sample-app
          image: itsmohammed/sample-app:latest
          env:
            - name: COLOR
              value: "blue"
          ports:
            - containerPort: 3000
