apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: sample-app
    color: blue # initially points to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
